CREATE TABLE  PUB_TABLE_COLUMNS
AS
SELECT T.OWNER,T.TABLE_NAME,C.COMMENTS AS TABLECOMMENTS,COL.COLUMN_NAME, COL.DATA_TYPE,COL.DATA_LENGTH,COL.DATA_SCALE,COL.DATA_PRECISION,COLC.COMMENTS AS COLUMNCOMMENTS ,COL.NULLABLE,TO_LOB(COL.DATA_DEFAULT) DATA_DEFAULT,
'20200101' PUBLISHDATE FROM SYS.ALL_ALL_TABLES T,SYS.ALL_TAB_COMMENTS C,SYS.ALL_TAB_COLUMNS COL,SYS.ALL_COL_COMMENTS COLC  
WHERE T.TABLE_NAME=C.TABLE_NAME  AND COL.TABLE_NAME=T.TABLE_NAME  AND COLC.TABLE_NAME=T.TABLE_NAME  
AND COL.COLUMN_NAME=COLC.COLUMN_NAME  
AND( T.OWNER ='TESTUSER'   )
--AND UPPER(T.TABLE_NAME)='RPT_TERMDISTRIBUTION_CHART'  
ORDER BY T.OWNER,T.TABLE_NAME,COL.COLUMN_ID

SELECT * FROM PUB_TABLE_COLUMNS WHERE  LENGTH (DATA_DEFAULT)>0


CREATE TABLE  PUB_TABLE_indexes
AS
select distinct T.TABLE_OWNER, t.Index_Name,t.table_name,t.column_name,t.COLUMN_POSITION,i.tablespace_name,i.uniqueness ,'20200101' PUBLISHDATE
from SYS.All_Ind_Columns t, sys.all_indexes i where t.index_name=i.index_name and t.table_name=i.table_name 
AND( T.TABLE_OWNER ='TESTUSER'  )
 ORDER BY T.TABLE_OWNER,Table_Name, Index_Name,COLUMN_POSITION
 
select * from PUB_TABLE_indexes

CREATE TABLE  PUB_TABLE_cons
AS
select ac.OWNER,ac.CONSTRAINT_NAME,ac.CONSTRAINT_TYPE,ac.TABLE_NAME,acc.COLUMN_NAME,acc.POSITION ,'20200101' PUBLISHDATE
         from sys.all_constraints ac ,sys.all_cons_columns acc   
         where ac.OWNER=acc.OWNER    
         and ac.CONSTRAINT_NAME=acc.CONSTRAINT_NAME   
         --and ac.TABLE_NAME='tableName.toUpperCase()'   
AND( ac.OWNER ='TESTUSER'  )
         and acc.POSITION IS NOT NULL 
         order by ac.CONSTRAINT_NAME, acc.POSITION
         
         
         
         
select * from PUB_TABLE_cons



CREATE TABLE  PUB_Source
as
select DISTINCT SC.OWNER,SC.name,SC.TYPE,SC.line,SC.TEXT ,'20200101' PUBLISHDATE from sys.All_Source SC 
where ( SC.OWNER ='TESTUSER'  )
  
CREATE TABLE  PUB_Views
as   
select AV.OWNER,AV.VIEW_NAME,  TO_LOB(AV.text) text  ,'20200101' PUBLISHDATE from sys.All_Views AV
where ( AV.OWNER ='TESTUSER'    )
  
  
